import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { useRef, useEffect } from 'react'

// Components
import { Steps } from '../components/steps'
import { ProgressBar } from '../components/progress-bar'

// Forms
import { Email } from '../components/forms/email'
import { Password } from '../components/forms/password'
import { UploadCarRegistration } from '../components/forms/upload-car-registration'
import { CarModel } from '../components/forms/car-model'
import { BankDetails } from '../components/forms/bank-details'

// Hooks
import { useLocalStorage } from '../hooks/useLocalStorage'

const stepProgress = (step: string | string[] | 0) => {
  switch (step) {
    case '0':
      return 20
    case '1':
      return 40
    case '2':
      return 60
    case '3':
      return 80
    case '4':
      return 100
    default:
      return 25
  }
}

const Home: NextPage = () => {
  const emailRef = useRef<HTMLDivElement>(null)
  const router = useRouter()
  const formStep = router.query.step ?? 0
  const [formStepValue, _setFormStepValue] = useLocalStorage<typeof formStep>('form-step', 0)

  useEffect(() => {
    router.push(`/?step=${formStepValue}`)
  }, [])

  return (
    <div>
      <Head>
        <title>Multi form app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed w-full bg-white z-50 top-0">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-5">
          <div className="mx-auto max-w-3xl">
            <Steps />
            {/* <div className="mt-5"> */}
            {/* <h2 className="font-semibold leading-6 text-indigo-600">Work with us</h2> */}
            {/* <h3 className="mt-2 text-3xl font-bold leading-8 tracking-tight text-indigo-600 sm:text-4xl">
                Our Process
              </h3> */}
            {/* </div> */}
          </div>
        </div>

        <ProgressBar percent={stepProgress(formStep)} />
      </div>

      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-28 mb-10">
        <main className="mx-auto max-w-3xl">
          <div className={`${formStep === '0' ? '' : 'opacity-50 cursor-not-allowed'}`}>
            <Email />
          </div>

          <div className={`mt-20 ${formStep === '1' ? '' : 'opacity-50 cursor-not-allowed'}`}>
            <Password />
          </div>

          <div className={`mt-20 ${formStep === '2' ? '' : 'opacity-50 cursor-not-allowed'}`}>
            <BankDetails />
          </div>

          <div className={`mt-20 ${formStep === '3' ? '' : 'opacity-50 cursor-not-allowed'}`}>
            <CarModel />
          </div>
          <div className={`mt-20 ${formStep === '4' ? '' : 'opacity-50 cursor-not-allowed'}`}>
            <UploadCarRegistration />
          </div>
        </main>
      </div>
    </div>
  )
}

export default Home
