import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { useRef } from 'react'

// Components
import { Steps } from '../components/steps'
// import { useLayoutEffect } from 'react'
// import Image from 'next/image'
import { ProgressBar } from '../components/progress-bar'

// Forms
import { Email } from '../components/forms/email'
import { Password } from '../components/forms/password'
import { UploadCarRegistration } from '../components/forms/upload-car-registration'
import { CarModel } from '../components/forms/car-model'
import { BankDetails } from '../components/forms/bank-details'

const Home: NextPage = () => {
  const emailRef = useRef<HTMLDivElement>(null)
  const passwordRef = useRef<HTMLDivElement>(null)
  const uploadRegistrationRef = useRef<HTMLDivElement>(null)
  const router = useRouter()
  const formStep = router.query.step ?? 0

  const goToStep = (step: number, asPath: string) => {
    router.push(`/?step=${step}`, asPath)

    passwordRef?.current.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' })
  }

  // useLayoutEffect(() => {
  //   goToStep(0, '/email')
  // }, [])

  return (
    <div className="overflow-hidden" style={{ height: '100vh' }}>
      <Head>
        <title>Multi form app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-10">
        <div className="mx-auto max-w-3xl">
          <Steps />
          <div className="mt-8">
            <h2 className="font-semibold leading-6 text-indigo-600">Work with us</h2>
            <h3 className="mt-2 text-3xl font-bold leading-8 tracking-tight text-gray-900 sm:text-4xl">Our Process</h3>
          </div>
        </div>
      </div>

      <ProgressBar percent={25} />

      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-10 mb-10">
        <main className="mx-auto max-w-3xl overflow-auto" style={{ height: 'calc(100vh - 300px)' }}>
          <div className={`${formStep === '0' ? '' : 'opacity-50 cursor-not-allowed'}`} ref={emailRef}>
            <Email />
            <button onClick={() => goToStep(4, '/bank-detail')}>scroll to password</button>
          </div>
          <div className={`mt-10 ${formStep === '1' ? '' : 'opacity-50 cursor-not-allowed'}`}>
            <Password />
          </div>
          <div className={`mt-20 ${formStep === '2' ? '' : 'opacity-50 cursor-not-allowed'}`}>
            <BankDetails />
          </div>
          <div className={`mt-20 ${formStep === '3' ? '' : 'opacity-50 cursor-not-allowed'}`}>
            <CarModel />
          </div>
          <div className={`mt-20 ${formStep === '4' ? '' : 'opacity-50 cursor-not-allowed'}`} ref={passwordRef}>
            <UploadCarRegistration />
          </div>
        </main>
      </div>
    </div>
  )
}

export default Home
