import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { useRef } from 'react'

// Components
import { Steps } from '../components/steps'
// import { useLayoutEffect } from 'react'
// import Image from 'next/image'
import { ProgressBar } from '../components/progress-bar'

// Forms
import { Email } from '../components/forms/email'
import { Password } from '../components/forms/password'
import { UploadCarRegistration } from '../components/forms/upload-car-registration'
import { CarModel } from '../components/forms/car-model'
import { BankDetails } from '../components/forms/bank-details'

const stepProgress = (step: string | string[] | 0) => {
  switch (step) {
    case '0':
      return 20
    case '1':
      return 40
    case '2':
      return 60
    case '3':
      return 80
    case '4':
      return 100
    default:
      return 25
  }
}

const Home: NextPage = () => {
  const onSubmit = (data: any) => console.log(data)
  const emailRef = useRef<HTMLDivElement>(null)
  const passwordRef = useRef<HTMLDivElement>(null)
  const uploadRegistrationRef = useRef<HTMLDivElement>(null)
  const router = useRouter()
  const formStep = router.query.step ?? 0

  const goToStep = (step: number, asPath: string) => {
    // router.push(`/?step=${step}`, asPath)
    // passwordRef?.current.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' })
  }

  // useLayoutEffect(() => {
  //   goToStep(0, '/email')
  // }, [])

  return (
    <div>
      <Head>
        <title>Multi form app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed w-full bg-white z-50 top-0">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-5">
          <div className="mx-auto max-w-3xl">
            <Steps />
            <div className="mt-5">
              {/* <h2 className="font-semibold leading-6 text-indigo-600">Work with us</h2> */}
              <h3 className="mt-2 text-3xl font-bold leading-8 tracking-tight text-indigo-600 sm:text-4xl">
                Our Process
              </h3>
            </div>
          </div>
        </div>

        <ProgressBar percent={stepProgress(formStep)} />
      </div>

      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-48 mb-10">
        <main className="mx-auto max-w-3xl">
          <div className={`mt-10`}>
            {/* <div className={`${formStep === '0' ? '' : 'opacity-50 cursor-not-allowed'}`} ref={emailRef}> */}
            <Email />
            {/* <button onClick={() => goToStep(4, '/bank-detail')}>scroll to password</button> */}
          </div>
          <div className={`mt-10`}>
            {/* <div className={`mt-10 ${formStep === '1' ? '' : 'opacity-50 cursor-not-allowed'}`}> */}
            <Password />
          </div>
          <div className={`mt-10`}>
            {/* <div className={`mt-20 ${formStep === '2' ? '' : 'opacity-50 cursor-not-allowed'}`}> */}
            <BankDetails />
          </div>
          <div className={`mt-10`}>
            {/* <div className={`mt-20 ${formStep === '3' ? '' : 'opacity-50 cursor-not-allowed'}`}> */}
            <CarModel />
          </div>
          {/* <div className={`mt-20 ${formStep === '4' ? '' : 'opacity-50 cursor-not-allowed'}`} ref={passwordRef}> */}
          <div className={`mt-10`}>
            <UploadCarRegistration />
          </div>
        </main>
      </div>
    </div>
  )
}

export default Home
